language: node_js
node_js:
  - "node"
  - "8"
  - "6"
before_script:
  - npm i -g eslint babel-eslint eslint-config-standard eslint-config-standard-react eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node eslint-plugin-react eslint-plugin-vue stylelint stylelint-scss stylelint-config-standard stylelint-config-recommended-scss @mapbox/stylelint-processor-arbitrary-tags
