language: node_js
node_js:
  - "node"
  - "8"
  - "6"
before_script:
  - npm i -g eslint eslint-config-standard eslint-config-standard-react eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node eslint-plugin-react
